# Generated by Django 3.2 on 2023-04-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0004_auto_20230412_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email_address',
            new_name='email',
        ),
    ]
