# Generated by Django 3.2 on 2023-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230227_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('4X6IN (10X15CM)', '4X6IN (10X15CM)'), ('5X7IN (13X18CM)', '5X7IN (13X18CM)'), ('8X10IN (20X25CM)', '8X10IN (20X25CM)')], default='4X6IN (10X15CM)', max_length=20),
        ),
    ]
