# Generated by Django 3.2 on 2023-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('4 x 6 inches', '4 x 6 inches'), ('5 x 7 inches', '5 x 7 inches'), ('8 x 10 inches', '8 x 10 inches'), ('8.5 x 11 inches', '8.5 x 11 inches')], default='4 x 6 inches', max_length=20),
        ),
    ]
