# Generated by Django 3.2 on 2023-04-08 17:23

from django.db import migrations
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=products.fields.CaseInsensitiveCharField(db_index=True, max_length=254, unique=True),
        ),
    ]
