# Generated by Django 3.2 on 2023-04-09 12:50

import django.core.validators
from django.db import migrations
import products.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230408_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=products.fields.CaseInsensitiveCharField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=products.fields.CaseInsensitiveCharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
